on:
  # Trigger analysis when pushing in master or pull requests, and when creating
  # a pull request.
  push:
    branches:
      - main
  pull_request:
      types: [opened, synchronize, reopened]
name: Main Workflow
jobs:
  sonarcloud:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        # Disabling shallow clone is recommended for improving relevancy of reporting
        fetch-depth: 0steps:
- uses: actions/checkout@v2
with:
fetch-depth: 0
name: Install dependencies
run: npm
- name: Test and coverage
run: npm jest --coverage
name: SonarCloud Scan
uses: SonarSource/sonarcloud-github-action@master
env:
GITHUB TOKEN: ${{ secrets.GITHUB_TOKEN }}
SONAR_TOKEN: ${{ secrets. SONARCLOUD_TOKEN }}

   